# CI Build. Runs on every commit to any branch.
jobs:
  - job: BuildAndTest
    variables:
      PYTHON_ENV: 'python'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
    - checkout: self
      submodules: true
      persistCredentials: true
    - script: npm install
      displayName: Install dependencies
    - script: npm run build
      displayName: Build project
    - script: npm test
      displayName: Run tests
